language: python
python:
  - "3.3"
  - "3.6"
install: "pip install -r requirements.txt"

services:
  - mongodb

script: nosetests

before_script:
  - mongoimport --db coder --collection users --file ./mocking/test_data.json
   --jsonArray
  - mongoimport --db coder --collection languages --file ./mocking/test_data
  _lang.json --jsonArray