language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"

services:
  - mongodb

script: nosetests

before_script:
  - bash mocking/mongodb_seeder.bash

notification:
  email:
    on_success: change
    on_failure: change

branches:
  only:
  - master
  - dev